In [3]:
!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.2 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 19.8 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip


In [6]:
import numpy as np

In [7]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [9]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [10]:
arr.max()

np.int64(95)

In [11]:
arr.argmax()

np.int64(0)

In [12]:
arr.min()

np.int64(9)

In [13]:
arr.argmin()

np.int64(7)

In [14]:
arr.mean()

np.float64(60.8)

In [17]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [18]:
mat = np.arange(0, 100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
row = 4
col = 6

In [25]:
mat[row, col]

np.int64(46)

In [28]:
mat[:, 1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [29]:
mat[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])